name: CI

on:
  push:
    paths-ignore: ['**.md', '**.adoc']
  pull_request:
    paths-ignore: ['**.md', '**.adoc']

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        # Not supported by Eldev; not terribly important.
        # '24.1', '24.2', '24.3'
        emacs_version: ['24.4',
                        '25.1', '25.2', '25.3',
                        '26.1', '26.2', '26.3',
                        '27.1', '27.2',
                        'snapshot']

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Test the project
      run: |
        eldev -p -dtT -C test --expect 10
        eldev -dtT -C compile --warnings-as-errors
